//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.03 at 12:58:36 PM IST 
//


package org.sci.classes;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sci.clases package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReportEntityReference_QNAME = new QName("", "entity_reference");
    private final static QName _ReportFiuRefNumber_QNAME = new QName("", "fiu_ref_number");
    private final static QName _TEntityRegistrationSHUrl_QNAME = new QName("", "url");
    private final static QName _TPersonTitle_QNAME = new QName("", "title");
    private final static QName _TPersonMiddleName_QNAME = new QName("", "middle_name");
    private final static QName _TAccountBeneficiaryComment_QNAME = new QName("", "beneficiary_comment");
    private final static QName _TAccountBeneficiary_QNAME = new QName("", "beneficiary");
    private final static QName _TAccountInstitutionName_QNAME = new QName("", "institution_name");
    private final static QName _ReportTransactionAuthorized_QNAME = new QName("", "authorized");
    private final static QName _ReportTransactionTransmodeComment_QNAME = new QName("", "transmode_comment");
    private final static QName _ReportTransactionTeller_QNAME = new QName("", "teller");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sci.clases
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Report }
     * 
     */
    public Report createReport() {
        return new Report();
    }

    /**
     * Create an instance of {@link TEntityRegistrationSH.ReportingObligations }
     * 
     */
    public TEntityRegistrationSH.ReportingObligations createTEntityRegistrationSHReportingObligations() {
        return new TEntityRegistrationSH.ReportingObligations();
    }

    /**
     * Create an instance of {@link TAccount.Signatory }
     * 
     */
    public TAccount.Signatory createTAccountSignatory() {
        return new TAccount.Signatory();
    }

    /**
     * Create an instance of {@link TPerson }
     * 
     */
    public TPerson createTPerson() {
        return new TPerson();
    }

    /**
     * Create an instance of {@link Report.Transaction.InvolvedParties }
     * 
     */
    public Report.Transaction.InvolvedParties createReportTransactionInvolvedParties() {
        return new Report.Transaction.InvolvedParties();
    }

    /**
     * Create an instance of {@link TAccount }
     * 
     */
    public TAccount createTAccount() {
        return new TAccount();
    }

    /**
     * Create an instance of {@link TEntityMyClient.Phones }
     * 
     */
    public TEntityMyClient.Phones createTEntityMyClientPhones() {
        return new TEntityMyClient.Phones();
    }

    /**
     * Create an instance of {@link TEntityRegistrationSUP.Addresses }
     * 
     */
    public TEntityRegistrationSUP.Addresses createTEntityRegistrationSUPAddresses() {
        return new TEntityRegistrationSUP.Addresses();
    }

    /**
     * Create an instance of {@link TEntityRegistrationRE.ReportingObligations }
     * 
     */
    public TEntityRegistrationRE.ReportingObligations createTEntityRegistrationREReportingObligations() {
        return new TEntityRegistrationRE.ReportingObligations();
    }

    /**
     * Create an instance of {@link TPersonRegistration }
     * 
     */
    public TPersonRegistration createTPersonRegistration() {
        return new TPersonRegistration();
    }

    /**
     * Create an instance of {@link TEntityRegistrationRE.Addresses }
     * 
     */
    public TEntityRegistrationRE.Addresses createTEntityRegistrationREAddresses() {
        return new TEntityRegistrationRE.Addresses();
    }

    /**
     * Create an instance of {@link TEntityRegistrationSH.Phones }
     * 
     */
    public TEntityRegistrationSH.Phones createTEntityRegistrationSHPhones() {
        return new TEntityRegistrationSH.Phones();
    }

    /**
     * Create an instance of {@link TEntityRegistrationSH.Addresses }
     * 
     */
    public TEntityRegistrationSH.Addresses createTEntityRegistrationSHAddresses() {
        return new TEntityRegistrationSH.Addresses();
    }

    /**
     * Create an instance of {@link TPersonMyClient.Addresses }
     * 
     */
    public TPersonMyClient.Addresses createTPersonMyClientAddresses() {
        return new TPersonMyClient.Addresses();
    }

    /**
     * Create an instance of {@link TEntity.DirectorId }
     * 
     */
    public TEntity.DirectorId createTEntityDirectorId() {
        return new TEntity.DirectorId();
    }

    /**
     * Create an instance of {@link Report.ReportIndicators }
     * 
     */
    public Report.ReportIndicators createReportReportIndicators() {
        return new Report.ReportIndicators();
    }

    /**
     * Create an instance of {@link TEntityRegistrationSH }
     * 
     */
    public TEntityRegistrationSH createTEntityRegistrationSH() {
        return new TEntityRegistrationSH();
    }

    /**
     * Create an instance of {@link TAccountMyClient.Signatory }
     * 
     */
    public TAccountMyClient.Signatory createTAccountMyClientSignatory() {
        return new TAccountMyClient.Signatory();
    }

    /**
     * Create an instance of {@link TPhone }
     * 
     */
    public TPhone createTPhone() {
        return new TPhone();
    }

    /**
     * Create an instance of {@link TEntity.Phones }
     * 
     */
    public TEntity.Phones createTEntityPhones() {
        return new TEntity.Phones();
    }

    /**
     * Create an instance of {@link TEntityMyClient }
     * 
     */
    public TEntityMyClient createTEntityMyClient() {
        return new TEntityMyClient();
    }

    /**
     * Create an instance of {@link TPerson.Phones }
     * 
     */
    public TPerson.Phones createTPersonPhones() {
        return new TPerson.Phones();
    }

    /**
     * Create an instance of {@link Report.Transaction.TFromMyClient }
     * 
     */
    public Report.Transaction.TFromMyClient createReportTransactionTFromMyClient() {
        return new Report.Transaction.TFromMyClient();
    }

    /**
     * Create an instance of {@link TPersonIdentification }
     * 
     */
    public TPersonIdentification createTPersonIdentification() {
        return new TPersonIdentification();
    }

    /**
     * Create an instance of {@link Report.Transaction.GoodsServices }
     * 
     */
    public Report.Transaction.GoodsServices createReportTransactionGoodsServices() {
        return new Report.Transaction.GoodsServices();
    }

    /**
     * Create an instance of {@link TPersonRegistrationInReport.Phones }
     * 
     */
    public TPersonRegistrationInReport.Phones createTPersonRegistrationInReportPhones() {
        return new TPersonRegistrationInReport.Phones();
    }

    /**
     * Create an instance of {@link Report.Activity }
     * 
     */
    public Report.Activity createReportActivity() {
        return new Report.Activity();
    }

    /**
     * Create an instance of {@link Report.Transaction }
     * 
     */
    public Report.Transaction createReportTransaction() {
        return new Report.Transaction();
    }

    /**
     * Create an instance of {@link TAddress }
     * 
     */
    public TAddress createTAddress() {
        return new TAddress();
    }

    /**
     * Create an instance of {@link TPerson.Addresses }
     * 
     */
    public TPerson.Addresses createTPersonAddresses() {
        return new TPerson.Addresses();
    }

    /**
     * Create an instance of {@link TParty }
     * 
     */
    public TParty createTParty() {
        return new TParty();
    }

    /**
     * Create an instance of {@link TEntityMyClient.DirectorId }
     * 
     */
    public TEntityMyClient.DirectorId createTEntityMyClientDirectorId() {
        return new TEntityMyClient.DirectorId();
    }

    /**
     * Create an instance of {@link Report.Transaction.TToMyClient }
     * 
     */
    public Report.Transaction.TToMyClient createReportTransactionTToMyClient() {
        return new Report.Transaction.TToMyClient();
    }

    /**
     * Create an instance of {@link TPersonMyClient }
     * 
     */
    public TPersonMyClient createTPersonMyClient() {
        return new TPersonMyClient();
    }

    /**
     * Create an instance of {@link Report.Transaction.TTo }
     * 
     */
    public Report.Transaction.TTo createReportTransactionTTo() {
        return new Report.Transaction.TTo();
    }

    /**
     * Create an instance of {@link TEntity }
     * 
     */
    public TEntity createTEntity() {
        return new TEntity();
    }

    /**
     * Create an instance of {@link TEntity.Addresses }
     * 
     */
    public TEntity.Addresses createTEntityAddresses() {
        return new TEntity.Addresses();
    }

    /**
     * Create an instance of {@link TEntityRegistrationRE }
     * 
     */
    public TEntityRegistrationRE createTEntityRegistrationRE() {
        return new TEntityRegistrationRE();
    }

    /**
     * Create an instance of {@link TTransItem }
     * 
     */
    public TTransItem createTTransItem() {
        return new TTransItem();
    }

    /**
     * Create an instance of {@link TEntityRegistrationSUP.Phones }
     * 
     */
    public TEntityRegistrationSUP.Phones createTEntityRegistrationSUPPhones() {
        return new TEntityRegistrationSUP.Phones();
    }

    /**
     * Create an instance of {@link TEntityRegistrationRE.Phones }
     * 
     */
    public TEntityRegistrationRE.Phones createTEntityRegistrationREPhones() {
        return new TEntityRegistrationRE.Phones();
    }

    /**
     * Create an instance of {@link TForeignCurrency }
     * 
     */
    public TForeignCurrency createTForeignCurrency() {
        return new TForeignCurrency();
    }

    /**
     * Create an instance of {@link TEntityMyClient.Addresses }
     * 
     */
    public TEntityMyClient.Addresses createTEntityMyClientAddresses() {
        return new TEntityMyClient.Addresses();
    }

    /**
     * Create an instance of {@link TPersonRegistration.Addresses }
     * 
     */
    public TPersonRegistration.Addresses createTPersonRegistrationAddresses() {
        return new TPersonRegistration.Addresses();
    }

    /**
     * Create an instance of {@link ReportPartyType }
     * 
     */
    public ReportPartyType createReportPartyType() {
        return new ReportPartyType();
    }

    /**
     * Create an instance of {@link TPersonRegistrationInReport }
     * 
     */
    public TPersonRegistrationInReport createTPersonRegistrationInReport() {
        return new TPersonRegistrationInReport();
    }

    /**
     * Create an instance of {@link Report.Activity.GoodsServices }
     * 
     */
    public Report.Activity.GoodsServices createReportActivityGoodsServices() {
        return new Report.Activity.GoodsServices();
    }

    /**
     * Create an instance of {@link TPersonRegistrationInReport.Addresses }
     * 
     */
    public TPersonRegistrationInReport.Addresses createTPersonRegistrationInReportAddresses() {
        return new TPersonRegistrationInReport.Addresses();
    }

    /**
     * Create an instance of {@link TEntityRegistrationSUP.ReportingObligations }
     * 
     */
    public TEntityRegistrationSUP.ReportingObligations createTEntityRegistrationSUPReportingObligations() {
        return new TEntityRegistrationSUP.ReportingObligations();
    }

    /**
     * Create an instance of {@link Report.Activity.ReportParties }
     * 
     */
    public Report.Activity.ReportParties createReportActivityReportParties() {
        return new Report.Activity.ReportParties();
    }

    /**
     * Create an instance of {@link TEntityRegistrationSUP }
     * 
     */
    public TEntityRegistrationSUP createTEntityRegistrationSUP() {
        return new TEntityRegistrationSUP();
    }

    /**
     * Create an instance of {@link TPersonRegistration.Phones }
     * 
     */
    public TPersonRegistration.Phones createTPersonRegistrationPhones() {
        return new TPersonRegistration.Phones();
    }

    /**
     * Create an instance of {@link Report.Transaction.TFrom }
     * 
     */
    public Report.Transaction.TFrom createReportTransactionTFrom() {
        return new Report.Transaction.TFrom();
    }

    /**
     * Create an instance of {@link Report.Transaction.LateDeposit }
     * 
     */
    public Report.Transaction.LateDeposit createReportTransactionLateDeposit() {
        return new Report.Transaction.LateDeposit();
    }

    /**
     * Create an instance of {@link TPersonMyClient.Phones }
     * 
     */
    public TPersonMyClient.Phones createTPersonMyClientPhones() {
        return new TPersonMyClient.Phones();
    }

    /**
     * Create an instance of {@link TAccountMyClient }
     * 
     */
    public TAccountMyClient createTAccountMyClient() {
        return new TAccountMyClient();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "entity_reference", scope = Report.class)
    public JAXBElement<String> createReportEntityReference(String value) {
        return new JAXBElement<String>(_ReportEntityReference_QNAME, String.class, Report.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fiu_ref_number", scope = Report.class)
    public JAXBElement<String> createReportFiuRefNumber(String value) {
        return new JAXBElement<String>(_ReportFiuRefNumber_QNAME, String.class, Report.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "url", scope = TEntityRegistrationSH.class)
    public JAXBElement<String> createTEntityRegistrationSHUrl(String value) {
        return new JAXBElement<String>(_TEntityRegistrationSHUrl_QNAME, String.class, TEntityRegistrationSH.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title", scope = TPerson.class)
    public JAXBElement<String> createTPersonTitle(String value) {
        return new JAXBElement<String>(_TPersonTitle_QNAME, String.class, TPerson.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "middle_name", scope = TPerson.class)
    public JAXBElement<String> createTPersonMiddleName(String value) {
        return new JAXBElement<String>(_TPersonMiddleName_QNAME, String.class, TPerson.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beneficiary_comment", scope = TAccount.class)
    public JAXBElement<String> createTAccountBeneficiaryComment(String value) {
        return new JAXBElement<String>(_TAccountBeneficiaryComment_QNAME, String.class, TAccount.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beneficiary", scope = TAccount.class)
    public JAXBElement<String> createTAccountBeneficiary(String value) {
        return new JAXBElement<String>(_TAccountBeneficiary_QNAME, String.class, TAccount.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "institution_name", scope = TAccount.class)
    public JAXBElement<String> createTAccountInstitutionName(String value) {
        return new JAXBElement<String>(_TAccountInstitutionName_QNAME, String.class, TAccount.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title", scope = TPersonRegistrationInReport.class)
    public JAXBElement<String> createTPersonRegistrationInReportTitle(String value) {
        return new JAXBElement<String>(_TPersonTitle_QNAME, String.class, TPersonRegistrationInReport.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "middle_name", scope = TPersonRegistrationInReport.class)
    public JAXBElement<String> createTPersonRegistrationInReportMiddleName(String value) {
        return new JAXBElement<String>(_TPersonMiddleName_QNAME, String.class, TPersonRegistrationInReport.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "url", scope = TEntityMyClient.class)
    public JAXBElement<String> createTEntityMyClientUrl(String value) {
        return new JAXBElement<String>(_TEntityRegistrationSHUrl_QNAME, String.class, TEntityMyClient.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title", scope = TPersonMyClient.class)
    public JAXBElement<String> createTPersonMyClientTitle(String value) {
        return new JAXBElement<String>(_TPersonTitle_QNAME, String.class, TPersonMyClient.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "middle_name", scope = TPersonMyClient.class)
    public JAXBElement<String> createTPersonMyClientMiddleName(String value) {
        return new JAXBElement<String>(_TPersonMiddleName_QNAME, String.class, TPersonMyClient.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "url", scope = TEntity.class)
    public JAXBElement<String> createTEntityUrl(String value) {
        return new JAXBElement<String>(_TEntityRegistrationSHUrl_QNAME, String.class, TEntity.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "url", scope = TEntityRegistrationRE.class)
    public JAXBElement<String> createTEntityRegistrationREUrl(String value) {
        return new JAXBElement<String>(_TEntityRegistrationSHUrl_QNAME, String.class, TEntityRegistrationRE.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title", scope = TPersonRegistration.class)
    public JAXBElement<String> createTPersonRegistrationTitle(String value) {
        return new JAXBElement<String>(_TPersonTitle_QNAME, String.class, TPersonRegistration.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "middle_name", scope = TPersonRegistration.class)
    public JAXBElement<String> createTPersonRegistrationMiddleName(String value) {
        return new JAXBElement<String>(_TPersonMiddleName_QNAME, String.class, TPersonRegistration.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "url", scope = TEntityRegistrationSUP.class)
    public JAXBElement<String> createTEntityRegistrationSUPUrl(String value) {
        return new JAXBElement<String>(_TEntityRegistrationSHUrl_QNAME, String.class, TEntityRegistrationSUP.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beneficiary_comment", scope = TAccountMyClient.class)
    public JAXBElement<String> createTAccountMyClientBeneficiaryComment(String value) {
        return new JAXBElement<String>(_TAccountBeneficiaryComment_QNAME, String.class, TAccountMyClient.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beneficiary", scope = TAccountMyClient.class)
    public JAXBElement<String> createTAccountMyClientBeneficiary(String value) {
        return new JAXBElement<String>(_TAccountBeneficiary_QNAME, String.class, TAccountMyClient.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "institution_name", scope = TAccountMyClient.class)
    public JAXBElement<String> createTAccountMyClientInstitutionName(String value) {
        return new JAXBElement<String>(_TAccountInstitutionName_QNAME, String.class, TAccountMyClient.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "authorized", scope = Report.Transaction.class)
    public JAXBElement<String> createReportTransactionAuthorized(String value) {
        return new JAXBElement<String>(_ReportTransactionAuthorized_QNAME, String.class, Report.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "transmode_comment", scope = Report.Transaction.class)
    public JAXBElement<String> createReportTransactionTransmodeComment(String value) {
        return new JAXBElement<String>(_ReportTransactionTransmodeComment_QNAME, String.class, Report.Transaction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "teller", scope = Report.Transaction.class)
    public JAXBElement<String> createReportTransactionTeller(String value) {
        return new JAXBElement<String>(_ReportTransactionTeller_QNAME, String.class, Report.Transaction.class, value);
    }

}
