//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.03 at 12:58:36 PM IST 
//


package org.sci.classes;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rentity_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="rentity_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="RE"/>
 *     &lt;enumeration value="SH"/>
 *     &lt;enumeration value="FIU"/>
 *     &lt;enumeration value="SUP"/>
 *     &lt;enumeration value="IND"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "rentity_type")
@XmlEnum
public enum RentityType {

    RE,
    SH,
    FIU,
    SUP,
    IND;

    public String value() {
        return name();
    }

    public static RentityType fromValue(String v) {
        return valueOf(v);
    }

}
