//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.03 at 12:58:36 PM IST 
//


package org.sci.classes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_phone complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_phone">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tph_contact_type" type="{}contact_type"/>
 *         &lt;element name="tph_communication_type" type="{}communication_type"/>
 *         &lt;element name="tph_country_prefix" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tph_number">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tph_extension" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="comments" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="4000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_phone", propOrder = {
    "tphContactType",
    "tphCommunicationType",
    "tphCountryPrefix",
    "tphNumber",
    "tphExtension",
    "comments"
})
public class TPhone {

    @XmlElement(name = "tph_contact_type", required = true)
    protected String tphContactType;
    @XmlElement(name = "tph_communication_type", required = true)
    protected String tphCommunicationType;
    @XmlElement(name = "tph_country_prefix")
    protected String tphCountryPrefix;
    @XmlElement(name = "tph_number", required = true)
    protected String tphNumber;
    @XmlElement(name = "tph_extension")
    protected String tphExtension;
    protected String comments;

    /**
     * Gets the value of the tphContactType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTphContactType() {
        return tphContactType;
    }

    /**
     * Sets the value of the tphContactType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTphContactType(String value) {
        this.tphContactType = value;
    }

    /**
     * Gets the value of the tphCommunicationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTphCommunicationType() {
        return tphCommunicationType;
    }

    /**
     * Sets the value of the tphCommunicationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTphCommunicationType(String value) {
        this.tphCommunicationType = value;
    }

    /**
     * Gets the value of the tphCountryPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTphCountryPrefix() {
        return tphCountryPrefix;
    }

    /**
     * Sets the value of the tphCountryPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTphCountryPrefix(String value) {
        this.tphCountryPrefix = value;
    }

    /**
     * Gets the value of the tphNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTphNumber() {
        return tphNumber;
    }

    /**
     * Sets the value of the tphNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTphNumber(String value) {
        this.tphNumber = value;
    }

    /**
     * Gets the value of the tphExtension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTphExtension() {
        return tphExtension;
    }

    /**
     * Sets the value of the tphExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTphExtension(String value) {
        this.tphExtension = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

}
